language: node_js
node_js:
  - node
script: yarn check-format
deploy:
  provider: gae
  keyfile: app-engine-secret.json
  project: utah-expungements-org
  skip_cleanup: true
  on:
    branch: master
before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_3bd2a9f02d5a_key -iv $encrypted_3bd2a9f02d5a_iv -in app-engine-secret.json.enc -out app-engine-secret.json -d
    fi
